apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: applications
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    #- matrix:
    #    generators:
    #      - git:
    #          repoURL: https://github.com/pluppen/kustomize_test.git
    #          revision: HEAD
    #          files:
    #          - path: apps/**/config.json
    #          pathParamPrefix: 'app'
    - git:
        repoURL: https://github.com/pluppen/kustomize_test.git
        revision: HEAD
        files:
        - path: 'apps/app-1/overlays/**/config.json'
        pathParamPrefix: 'overlay'
  template:
    metadata:
      name: 'app-1-{{.overlay.path.basename}}'
    spec:
      project: "default"
      source:
        repoURL: https://github.com/argoproj/argo-cd.git
        targetRevision: HEAD
        path: ''#'{{.app.path.path}}'
      destination:
        server: '' #'{{ .clusterURL }}'
        namespace: '{{ .appName }}'
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
